// <auto-generated />
using System;
using CalculadoraPekus.API.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraPekus.API.Migrations
{
    [DbContext(typeof(CalculadoraContexto))]
    partial class CalculadoraContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculadoraPekus.Models.CalculoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCalculo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Resultado")
                        .HasColumnType("float");

                    b.Property<double>("ValorA")
                        .HasColumnType("float");

                    b.Property<double>("ValorB")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Calculos");
                });
#pragma warning restore 612, 618
        }
    }
}
